/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pemilihandokter;

/**
 *
 * @author Moklet
 */
public class pilihdokter extends javax.swing.JFrame {

    /**
     * Creates new form pilihdokter
     */
    public pilihdokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cb = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        Ds = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Kw = new javax.swing.JTextField();
        Wp = new javax.swing.JTextField();
        Status = new javax.swing.JTextField();
        Goldar = new javax.swing.JTextField();
        Jk = new javax.swing.JTextField();
        Usia = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(null);

        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu --", "DR. Farras Yassar", "DR. Anisa Putri", "DR. Harun Fajar" }));
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });
        jPanel2.add(cb);
        cb.setBounds(120, 60, 130, 30);

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));
        jPanel3.setLayout(null);

        Ds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DsActionPerformed(evt);
            }
        });
        jPanel3.add(Ds);
        Ds.setBounds(180, 460, 170, 30);

        jLabel12.setText("Dokter Spesialis");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(50, 460, 130, 30);

        Kw.setEnabled(false);
        Kw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KwActionPerformed(evt);
            }
        });
        jPanel3.add(Kw);
        Kw.setBounds(150, 270, 170, 30);

        Wp.setEnabled(false);
        Wp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WpActionPerformed(evt);
            }
        });
        jPanel3.add(Wp);
        Wp.setBounds(150, 310, 170, 30);

        Status.setEnabled(false);
        Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusActionPerformed(evt);
            }
        });
        jPanel3.add(Status);
        Status.setBounds(150, 230, 170, 30);

        Goldar.setEnabled(false);
        Goldar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoldarActionPerformed(evt);
            }
        });
        jPanel3.add(Goldar);
        Goldar.setBounds(150, 190, 170, 30);

        Jk.setEnabled(false);
        Jk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JkActionPerformed(evt);
            }
        });
        jPanel3.add(Jk);
        Jk.setBounds(150, 150, 170, 30);

        Usia.setEnabled(false);
        Usia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsiaActionPerformed(evt);
            }
        });
        jPanel3.add(Usia);
        Usia.setBounds(150, 110, 170, 30);

        Alamat.setEnabled(false);
        Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatActionPerformed(evt);
            }
        });
        jPanel3.add(Alamat);
        Alamat.setBounds(150, 70, 170, 30);

        Nama.setEnabled(false);
        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        jPanel3.add(Nama);
        Nama.setBounds(150, 30, 170, 30);

        jLabel13.setText("Nama");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(20, 30, 130, 30);

        jLabel5.setText("Alamat");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 70, 130, 30);

        jLabel6.setText("Usia");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 110, 120, 30);

        jLabel7.setText("Jenis Kelamin");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 150, 130, 30);

        jLabel8.setText("Golongan Darah");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 190, 130, 30);

        jLabel9.setText("Status");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 230, 130, 30);

        jLabel10.setText("Kewarganegaraan");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 270, 130, 30);

        jLabel11.setText("Waktu Praktek");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(20, 310, 130, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(30, 120, 350, 360);

        jLabel3.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel3.setText("Pemilihan Dokter");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(120, 20, 210, 30);

        jLabel2.setText("Pilih Dokter");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 60, 80, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-10, -10, 430, 510);

        setBounds(0, 0, 407, 533);
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatActionPerformed

    private void UsiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsiaActionPerformed

    private void JkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JkActionPerformed

    private void GoldarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoldarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoldarActionPerformed

    private void StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusActionPerformed

    private void KwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KwActionPerformed

    private void WpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WpActionPerformed

    private void DsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DsActionPerformed

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        if(cb.getSelectedItem().equals("DR. Farras Yassar")){ 
            Nama.setText("DR. Farras Yassar "); 
            Alamat.setText("Jl. Surabaya 16, Malang"); 
            Usia.setText("20 Tahun"); 
            Jk.setText("Laki-Laki"); 
            Goldar.setText("A"); 
            Status.setText("Belum Menikah "); 
            Kw.setText("Indonesia"); 
            Wp.setText("Dokter Umum"); 
            Ds.setText(" Pagi (07.00-15.00)"); 
        } 
        else 
        if(cb.getSelectedItem().equals("DR. Anisa Putri")){ 
            Nama.setText("DR. Anisa Putri"); 
            Alamat.setText("Jl. Veteran 3, Malang"); 
            Usia.setText("20 Tahun"); 
            Jk.setText("Perempuan"); 
            Goldar.setText("O"); 
            Status.setText("Belum Menikah"); 
            Kw.setText("Indonesia"); 
            Wp.setText("Dokter Gigi"); 
            Ds.setText(" Sore (16.00-22.00)"); 
        } 
        else 
        if(cb.getSelectedItem().equals("DR. Harun Fajar")){ 
            Nama.setText("DR. Harun Fajar "); 
            Alamat.setText("Jl. Bandung 9, Malang"); 
            Usia.setText("20 Tahun"); 
            Jk.setText("Laki-Laki"); 
            Goldar.setText("B"); 
            Status.setText("Belum Menikah"); 
            Kw.setText("Indonesia"); 
            Wp.setText("Dokter Gizi"); 
            Ds.setText(" Malam (22.00-06.00)");
        }
    }//GEN-LAST:event_cbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pilihdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pilihdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pilihdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pilihdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pilihdokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField Ds;
    private javax.swing.JTextField Goldar;
    private javax.swing.JTextField Jk;
    private javax.swing.JTextField Kw;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Status;
    private javax.swing.JTextField Usia;
    private javax.swing.JTextField Wp;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
